---

- name: Create proxy-users group
  group:
    name: proxy-users
    system: no
    state: present

- name: Install proxy
  ansible.builtin.package:
    name: squid
    state: present
    autoremove: yes

- name: Deploy templates
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    decrypt: "{{item.decrypt}}"
  with_items:
    - { src: "squid.conf.j2",    dest: "/etc/squid/squid.conf",   mode: "0644", owner: "root", group: "root", decrypt: "no" }
    - { src: "sudoers.proxy.j2", dest: "/etc/sudoers.d/20-proxy", mode: "0440", owner: "root", group: "root", decrypt: "no" }

- name: Create Proxy users
  user:
    name: "{{ item.user }}"
    comment: "{{ item.user }} proxy user"
    password: "{{ item.password | password_hash('sha512') }}"
    group: proxy-users
    shell: /sbin/nologin
    home: "/nonexistent"
    create_home: no
  with_items:
  - "{{ squid_users }}"
  when: squid_users is defined

- name: Start proxy server
  ansible.builtin.service:
    name: squid
    state: restarted
    enabled: yes

- name: ReStart proxy server
  ansible.builtin.service:
    name: squid
    state: restarted
    enabled: yes
  when: squid_restart is defined and squid_restart=="yes"

- name: Service massage
  debug:
    msg: "You can use --extra-vars='squid_restart=yes' to restart Squid service"

- name: Check squid status
  shell: service squid status
  register: sOut

- debug:
    var: sOut.stdout_lines
