name: Push to Galaxy

env:
  ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
  GitUser: BestianCode
  GitRepo: ansible.role.anonymous_proxy

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  push:
    name: 'Push to Galaxy'

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - run: export
#      - uses: actions/setup-python@v5
#        with:
#          python-version: '3.x'
#      - run: pip install ansible
#      - run: |
#          ansible-galaxy role import --token ${{ env.ANSIBLE_GALAXY_TOKEN }} ${{ env.GitUser }} ${{ env.GitRepo }}
